### ISSUE TITLE
feat: support go1.17

### ISSUE THREAD

**Issue by joesonw** [ogen-go/ogen#340]
I am not sure how many of the community has upgrded to 1.18. What I know is most production environments are still at 1.17 or 1.16. This renders this project not feasible for actual production useage

**Comment by ernado** [comment]
Current project status is [experimental](https://go-faster.org/docs/projects/status/#experimental), probably we reach beta when go1.19 will be already out.

**Comment by tdakkota** [comment]
Go 1.19 has been released two weeks ago, so 1.17 is no longer supported. We need a clear decision.

**Cons**
- Go 1.17 is no longer supported due to Go release policy.
- We are using features of Go 1.18. _(includes generated code)_
  - We are using `net/netip`.
  - We are using generics in `jx` and `errors`.
- We can use features of Go 1.18 in the future.
  - Go 1.18 adds `continue` and `break` keywords into `text/template` language.
  - We can use generics for optionals to reduce boilerplate as planned in roadmap.
  - (?) Something else?
- The more versions we support, the more is developing cost.

**Pros**
- Some non-standard(cloud-managed, gopherjs) runtimes still don't support 1.18 or generics.
- Actually, we can use 1.18+ inside generator, but do not use it in generated code.
  - Also, we can generate two files: for >=1.18 and for <=1.17.

pinging @ernado @shadowspore

**Comment by ernado** [comment]
General decision for all go-faster-maintained projects: Drop 1.17 per Go release policy, use generics.
